# Generated by Django 5.0.1 on 2024-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('price', models.IntegerField()),
                ('cat', models.CharField(choices=[( 'VEG DISHES',1),('NON-VEG DISHES',2),('VEG STARTUP',3),('NON_VEJ STARTUP',4),('DESSERT',5),('COLD-DRINKS',6),('CHINESE',7)])),
                ('pdetails', models.CharField(max_length=50, verbose_name='Product Details')),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
